name: Auto PR approve workflow
on:
  issue_comment:                                     
    types: [created, edited, deleted]
    
env:
  PR_NUMBER: ${{ github.event.issue.number }}
    
jobs:
  approve:
    runs-on: [self-hosted, linux, amd64]
    steps:
      - name: Check comments
        uses: khan/pull-request-comment-trigger@v1.1.0
        id: check
        with:
          trigger: '@approve'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: Approve the PR if condition satisfies.
        if: steps.check.outputs.triggered == 'true'
        uses: hmarr/auto-approve-action@v3
        with:
          review-message: "Auto approved PR, but before merging, please specify the reason."
          pull-request-number: ${{ env.PR_NUMBER }}

      - name: Notify on slack 
        if: steps.check.outputs.triggered == 'true'
        run: |
          USERNAME=`echo ${{ github.actor }} | tr '-' '_'`
          USERID=`cat slack.json | jq -r ".\"$USERNAME\""`
          echo "Alerting for failed workflow - ${{ github.event.workflow_run.name }}"
          echo ${{ github.event.issue.html_url }}
